owner: jojoxd
repo: site-status

status-website:
  cname: status.jojoxd.nl
  
  name: JojoXD Services Status
  introTitle: "JojoXD Services Status"
  
  theme: dark
  
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

sites:
  - name: JojoXD.nl
    url: https://jojoxd.nl
    maxResponseTime: 750
  
  - name: Desu
    url: https://desu.jojoxd.nl
    maxResponseTime: 750
  
  - name: Anime RSS Filter (v2)
    url: https://desu.jojoxd.nl/anime-rss-filter
    maxResponseTime: 1000
  
  - name: BakaBot
    url: https://desu.jojoxd.nl/bakabot

workflowSchedule:
  graphs: "10,40 * * * *"
  responseTime: "0,30 * * * *"
